spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genera?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never  # 关闭自动执行schema.sql，因为表已经存在

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志打印
  type-aliases-package: com.example.auth.entity  # 实体类包路径 