# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
    
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password:    # 如果没有设置密码，此处留空
    timeout: 10s
    
  # 邮件配置
  mail:
    host: smtp.qq.com  # 以QQ邮箱为例
    port: 465         # QQ邮箱的SSL端口
    username: 3129180887@qq.com    # 您的邮箱地址
    password: gzhbshwhaoyyddih        # 您的邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true          # 启用SSL
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.auth.model.entity
  configuration:
    map-underscore-to-camel-case: true
    
# 日志配置
logging:
  level:
    com.example.auth: debug

sql:
  init:
    mode: never  # 关闭自动执行schema.sql，因为表已经存在 

# 系统信息配置
system:
  info:
    title: 统一认证中心
    description: Unified Authentication Center
    version: 1.0.0
    copyright: © 2024 Your Company. All rights reserved.
    sys-belone: test  # 添加系统标识 

jwt:
  secret: your_jwt_secret_key_must_be_at_least_256_bits_long_so_make_it_long_enough 